<a href="https://colab.research.google.com/github/PatrickRuan/ML100Days/blob/master/homework/Day_034_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [2]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [3]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [5]:
np.where(y==1) # index at 0:39
np.where(y==0) # index at 40~ 199

(array([ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
        183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
        196, 197, 198, 199]),)

In [10]:
y_1_index, y_0_index = np.where(y==1)[0], np.where(y==0)[0] # 選出 y 等於 1 的 index 與 y 等於 0 的 index

In [12]:
from sklearn.model_selection import train_test_split
train_x1, test_x1, train_y1, test_y1 = train_test_split(X[y_1_index], y[y_1_index], test_size = 20)
train_x0, test_x0, train_y0, test_y0 = train_test_split(X[y_0_index], y[y_0_index], test_size = 20)

In [15]:
test_y0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [16]:
x_train, y_train = np.concatenate([train_x1, train_x0]), np.concatenate([train_y1, train_y0])
x_test, y_test = np.concatenate([test_x1, test_x0]), np.concatenate([test_y1, test_y0])


In [20]:
for testx, testy in zip(x_test, y_test):
  print(testx, testy)

[70 71 72 73 74] 1.0
[130 131 132 133 134] 1.0
[65 66 67 68 69] 1.0
[45 46 47 48 49] 1.0
[80 81 82 83 84] 1.0
[10 11 12 13 14] 1.0
[175 176 177 178 179] 1.0
[195 196 197 198 199] 1.0
[30 31 32 33 34] 1.0
[165 166 167 168 169] 1.0
[115 116 117 118 119] 1.0
[120 121 122 123 124] 1.0
[190 191 192 193 194] 1.0
[35 36 37 38 39] 1.0
[160 161 162 163 164] 1.0
[55 56 57 58 59] 1.0
[95 96 97 98 99] 1.0
[25 26 27 28 29] 1.0
[90 91 92 93 94] 1.0
[105 106 107 108 109] 1.0
[700 701 702 703 704] 0.0
[815 816 817 818 819] 0.0
[900 901 902 903 904] 0.0
[415 416 417 418 419] 0.0
[240 241 242 243 244] 0.0
[750 751 752 753 754] 0.0
[455 456 457 458 459] 0.0
[835 836 837 838 839] 0.0
[300 301 302 303 304] 0.0
[620 621 622 623 624] 0.0
[360 361 362 363 364] 0.0
[960 961 962 963 964] 0.0
[510 511 512 513 514] 0.0
[370 371 372 373 374] 0.0
[950 951 952 953 954] 0.0
[265 266 267 268 269] 0.0
[850 851 852 853 854] 0.0
[555 556 557 558 559] 0.0
[525 526 527 528 529] 0.0
[985 986 987 988 989] 0.0
